name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
        paths:
            - 'src/**'
            - 'public/**'
            - 'package.json'
            - 'package-lock.json'
            - '.github/workflows/deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            
            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
              env:
                CI: false

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GH_ACTION_TOKEN }}
                publish_dir: ./build